<?xml version="1.0" encoding="utf-8"?><Database Name="dbBarcodeNab" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=1.179.133.222,2018;Initial Catalog=dbBarcodeNab;User ID=sa" SettingsObjectName="StockControl.Properties.Settings" SettingsPropertyName="dbBarcodeNabConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ErrorLog" Member="ErrorLogs">
    <Type Name="ErrorLog">
      <Column Name="ErrorLogNo" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorMethod" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ErrorLogMessage" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ErrorLogScreen" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ErrorLogDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ErrorLogBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMachineName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorLoginMachineName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Layout_Screen" Member="Layout_Screens">
    <Type Name="Layout_Screen">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Screen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Control" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="C_Columns" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="W_width" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="H_higth" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Seq" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OpenForm" Member="OpenForms">
    <Type Name="OpenForm">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RootName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NodeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TypeNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LinkNode" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DialogFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_History" Member="tb_Histories">
    <Type Name="tb_History">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScreenName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApplicationNme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="RefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Path" Member="tb_Paths">
    <Type Name="tb_Path">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PathCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PathDetail" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PathFile" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_WorkDays" Member="tb_WorkDays">
    <Type Name="tb_WorkDay">
      <Column Name="YYYY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MMM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WorkDays" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_WorkHour" Member="tb_WorkHours">
    <Type Name="tb_WorkHour">
      <Column Name="WorkHour" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_LocationlWH" Member="tb_LocationlWHs">
    <Type Name="tb_LocationlWH">
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ListQueue" Member="tb_ListQueues">
    <Type Name="tb_ListQueue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ListDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListRefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ReceiveHD" Member="tb_ReceiveHDs">
    <Type Name="tb_ReceiveHD">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RCNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RCVendorNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCVendorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCInvoiceNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCRemark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ExportList" Member="tb_ExportLists">
    <Type Name="tb_ExportList">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Revision" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ETDDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETADate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippingBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IssueBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ReceiveTemp" Member="tb_ReceiveTemps">
    <Type Name="tb_ReceiveTemp">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SNP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScanQR" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_GuideLineLot" Member="tb_GuideLineLots">
    <Type Name="tb_GuideLineLot">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SNP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_LocalListDetail" Member="tb_LocalListDetails">
    <Type Name="tb_LocalListDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerItem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Plant" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IssueBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LConfirm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LConfirmDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_LocalShipment" Member="tb_LocalShipments">
    <Type Name="tb_LocalShipment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SNP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ExportList" Member="tb_ExportList1s">
    <Type Name="tb_ExportList1">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Revision" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ETDDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETADate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippingBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IssueBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ExportShipment" Member="tb_ExportShipments">
    <Type Name="tb_ExportShipment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="QtyPL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QtyOfTG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSTMPO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConfirmDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STDPacking" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LConfirm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ship" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ReceiveLine" Member="tb_ReceiveLines">
    <Type Name="tb_ReceiveLine">
      <Column Name="RCNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PONo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="LocalLotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TAG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SNP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_UserMachine" Member="tb_UserMachines">
    <Type Name="tb_UserMachine">
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_User" Member="tb_Users">
    <Type Name="tb_User">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ItemList" Member="tb_ItemLists">
    <Type Name="tb_ItemList">
      <Column Name="CodeNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DescriptionItem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PathImage" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="ShelfNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocationWH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SPN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tb_UserPermission" Member="tb_UserPermissions">
    <Type Name="tb_UserPermission">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LayoutName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScreenName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_CheckStock" Member="tb_CheckStocks">
    <Type Name="tb_CheckStock">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CheckNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_CheckStockList" Member="tb_CheckStockLists">
    <Type Name="tb_CheckStockList">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CheckNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InputQty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diff" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Revision" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExclusionClass" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StorageWorkCenter" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StorageWorkCenterName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CurrentInventory" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InventoryValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockBeforeInventory" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PhysicalInventoryValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_CheckStockTempCheck" Member="tb_CheckStockTempChecks">
    <Type Name="tb_CheckStockTempCheck">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CheckNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CheckMachine" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CheckBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Package" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SNP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ofTAG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TempPrintSupplier" Member="TempPrintSuppliers">
    <Type Name="TempPrintSupplier">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PONo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SNP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OfTAG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QRCode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TAGValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TAGRemark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_HistoryPrintSupplier" Member="tb_HistoryPrintSuppliers">
    <Type Name="tb_HistoryPrintSupplier">
      <Column Name="PONo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PrintTAG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TEMPTAG" Member="TEMPTAGs">
    <Type Name="TEMPTAG">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TempNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SNP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OfTAG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QRCode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TAGValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TAGRemark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_LotNo" Member="tb_LotNos">
    <Type Name="tb_LotNo">
      <Column Name="LotDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_GenerateLotMap" Member="tb_GenerateLotMaps">
    <Type Name="tb_GenerateLotMap">
      <Column Name="Daysx" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KeyLot" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductTAG" Member="tb_ProductTAGs">
    <Type Name="tb_ProductTAG">
      <Column Name="Machine" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Seq" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSTMShot" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="CSTMItem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustItem2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OFTAG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PathPic" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BOMNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QRCode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tb_MapItemTPICS" Member="tb_MapItemTPICs">
    <Type Name="tb_MapItemTPIC">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ac" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustItemNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustItemName" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DWG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Sp_ADM03_OpenFormSelect" Method="Sp_ADM03_OpenFormSelect">
    <ElementType Name="Sp_ADM03_OpenFormSelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RootName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NodeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TypeNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LinkNode" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DialogFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BackupDatabase" Method="sp_BackupDatabase">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getDateVachar" Method="getDateVachar" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.sp_DeleteLog" Method="sp_DeleteLog">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getDate" Method="getDate" IsComposable="true">
    <Return Type="System.DateTime" />
  </Function>
  <Function Name="dbo.sp_SC_001_SelectScreen" Method="sp_SC_001_SelectScreen">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_SC_001_SelectScreenResult">
      <Column Name="Layout" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sp_GetNameControl_001" Method="Sp_GetNameControl_001">
    <Parameter Name="ControlNo" Parameter="controlNo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Action" Parameter="action" Type="System.Int32" DbType="Int" />
    <ElementType Name="Sp_GetNameControl_001Result">
      <Column Name="GetNo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SC_002_SelectListQueue" Method="sp_SC_002_SelectListQueue">
    <ElementType Name="sp_SC_002_SelectListQueueResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ListDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ListRefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_003_Compare_CheckStock" Method="sp_003_Compare_CheckStock">
    <Parameter Name="CheckNo" Parameter="checkNo" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_001_TPIC_SelectItem" Method="sp_001_TPIC_SelectItem">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_001_TPIC_SelectItemResult">
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="WorkCenterNo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="WorkCenterName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Parent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SHELVES" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ReqLot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="VENDOR" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VendorName1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PahtImage" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="LeadTime" Type="System.Decimal" DbType="Decimal(29,0)" CanBeNull="true" />
      <Column Name="LotSize" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="MinimumStock" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="HOKAN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="InspectionReq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InputDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CurrentStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_002_TPIC_SelectPO" Method="sp_002_TPIC_SelectPO">
    <Parameter Name="PONo" Parameter="pONo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Vendor" Parameter="vendor" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ck" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Date1" Parameter="date1" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Date2" Parameter="date2" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_002_TPIC_SelectPOResult">
      <Column Name="PORDER" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="LotSize" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BUMO" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VENDOR" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OrderQty" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="BeforeIns" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalResults" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Revision" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="RATE" Type="System.Decimal" DbType="Decimal(29,0) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(29,4) NOT NULL" CanBeNull="false" />
      <Column Name="INVOICENO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INPUTUSER" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PrintTAG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_R_001_Report_CheckStock" Method="sp_R_001_Report_CheckStock">
    <Parameter Name="CheckNo1" Parameter="checkNo1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CheckNo2" Parameter="checkNo2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_R_001_Report_CheckStockResult">
      <Column Name="CheckNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="InputQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diff" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Revision" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExclusionClass" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StorageWorkCenter" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StorageWorkCenterName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CurrentInventory" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InventoryValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="StockBeforeInventory" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PhysicalInventoryValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_E_001_Excel_tb_CheckStockTempCheck" Method="sp_E_001_Excel_tb_CheckStockTempCheck">
    <Parameter Name="CheckNo" Parameter="checkNo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_E_001_Excel_tb_CheckStockTempCheckResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CheckMachine" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CheckBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Package" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SNP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ofTAG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_003_TPIC_GETBOMNo" Method="sp_003_TPIC_GETBOMNo">
    <Parameter Name="BOMNo" Parameter="bOMNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="AC" Parameter="aC" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_003_TPIC_GETBOMNoResult">
      <Column Name="PORDER" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="LotSize" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BUMO" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VENDOR" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OrderQty" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="BeforeIns" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalResults" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Revision" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="RATE" Type="System.Decimal" DbType="Decimal(29,0) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(29,4) NOT NULL" CanBeNull="false" />
      <Column Name="INVOICENO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INPUTUSER" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustItemName" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="CustItemNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CSTMName" Type="System.String" DbType="VarChar(47) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_004_TPIC_SelectWO" Method="sp_004_TPIC_SelectWO">
    <Parameter Name="PONo" Parameter="pONo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Vendor" Parameter="vendor" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ck" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Date1" Parameter="date1" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Date2" Parameter="date2" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_004_TPIC_SelectWOResult">
      <Column Name="PORDER" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="LotSize" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BUMO" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VENDOR" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OrderQty" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="BeforeIns" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalResults" Type="System.Decimal" DbType="Decimal(29,2) NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Revision" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="RATE" Type="System.Decimal" DbType="Decimal(29,0) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(29,4) NOT NULL" CanBeNull="false" />
      <Column Name="INVOICENO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INPUTUSER" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PrintTAG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_005_TPIC_SelectMapping" Method="sp_005_TPIC_SelectMapping">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_005_TPIC_SelectMappingResult">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustItemNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustItemName" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DWG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>