#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbBarcodeNab")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertErrorLog(ErrorLog instance);
    partial void UpdateErrorLog(ErrorLog instance);
    partial void DeleteErrorLog(ErrorLog instance);
    partial void InsertOpenForm(OpenForm instance);
    partial void UpdateOpenForm(OpenForm instance);
    partial void DeleteOpenForm(OpenForm instance);
    partial void Inserttb_History(tb_History instance);
    partial void Updatetb_History(tb_History instance);
    partial void Deletetb_History(tb_History instance);
    partial void Inserttb_Path(tb_Path instance);
    partial void Updatetb_Path(tb_Path instance);
    partial void Deletetb_Path(tb_Path instance);
    partial void Inserttb_WorkDay(tb_WorkDay instance);
    partial void Updatetb_WorkDay(tb_WorkDay instance);
    partial void Deletetb_WorkDay(tb_WorkDay instance);
    partial void Inserttb_LocationlWH(tb_LocationlWH instance);
    partial void Updatetb_LocationlWH(tb_LocationlWH instance);
    partial void Deletetb_LocationlWH(tb_LocationlWH instance);
    partial void Inserttb_ReceiveHD(tb_ReceiveHD instance);
    partial void Updatetb_ReceiveHD(tb_ReceiveHD instance);
    partial void Deletetb_ReceiveHD(tb_ReceiveHD instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::StockControl.Properties.Settings.Default.dbBarcodeNabConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ErrorLog> ErrorLogs
		{
			get
			{
				return this.GetTable<ErrorLog>();
			}
		}
		
		public System.Data.Linq.Table<Layout_Screen> Layout_Screens
		{
			get
			{
				return this.GetTable<Layout_Screen>();
			}
		}
		
		public System.Data.Linq.Table<OpenForm> OpenForms
		{
			get
			{
				return this.GetTable<OpenForm>();
			}
		}
		
		public System.Data.Linq.Table<tb_History> tb_Histories
		{
			get
			{
				return this.GetTable<tb_History>();
			}
		}
		
		public System.Data.Linq.Table<tb_Path> tb_Paths
		{
			get
			{
				return this.GetTable<tb_Path>();
			}
		}
		
		public System.Data.Linq.Table<tb_WorkDay> tb_WorkDays
		{
			get
			{
				return this.GetTable<tb_WorkDay>();
			}
		}
		
		public System.Data.Linq.Table<tb_WorkHour> tb_WorkHours
		{
			get
			{
				return this.GetTable<tb_WorkHour>();
			}
		}
		
		public System.Data.Linq.Table<tb_LocationlWH> tb_LocationlWHs
		{
			get
			{
				return this.GetTable<tb_LocationlWH>();
			}
		}
		
		public System.Data.Linq.Table<tb_User> tb_Users
		{
			get
			{
				return this.GetTable<tb_User>();
			}
		}
		
		public System.Data.Linq.Table<tb_ListQueue> tb_ListQueues
		{
			get
			{
				return this.GetTable<tb_ListQueue>();
			}
		}
		
		public System.Data.Linq.Table<tb_ReceiveHD> tb_ReceiveHDs
		{
			get
			{
				return this.GetTable<tb_ReceiveHD>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ADM03_OpenFormSelect")]
		public ISingleResult<Sp_ADM03_OpenFormSelectResult> Sp_ADM03_OpenFormSelect()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_ADM03_OpenFormSelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BackupDatabase")]
		public int sp_BackupDatabase()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDateVachar", IsComposable=true)]
		public string getDateVachar()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteLog")]
		public int sp_DeleteLog()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDate", IsComposable=true)]
		public System.Nullable<System.DateTime> getDate()
		{
			return ((System.Nullable<System.DateTime>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_001_TPIC_SelectItem")]
		public ISingleResult<sp_001_TPIC_SelectItemResult> sp_001_TPIC_SelectItem()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_001_TPIC_SelectItemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_002_TPIC_SelectPO")]
		public ISingleResult<sp_002_TPIC_SelectPOResult> sp_002_TPIC_SelectPO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_002_TPIC_SelectPOResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ErrorLog")]
	public partial class ErrorLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ErrorLogNo;
		
		private string _ErrorMethod;
		
		private string _ErrorLogMessage;
		
		private string _ErrorLogScreen;
		
		private System.Nullable<System.DateTime> _ErrorLogDateTime;
		
		private string _ErrorLogBy;
		
		private string _ErrorMachineName;
		
		private string _ErrorLoginMachineName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnErrorLogNoChanging(long value);
    partial void OnErrorLogNoChanged();
    partial void OnErrorMethodChanging(string value);
    partial void OnErrorMethodChanged();
    partial void OnErrorLogMessageChanging(string value);
    partial void OnErrorLogMessageChanged();
    partial void OnErrorLogScreenChanging(string value);
    partial void OnErrorLogScreenChanged();
    partial void OnErrorLogDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnErrorLogDateTimeChanged();
    partial void OnErrorLogByChanging(string value);
    partial void OnErrorLogByChanged();
    partial void OnErrorMachineNameChanging(string value);
    partial void OnErrorMachineNameChanged();
    partial void OnErrorLoginMachineNameChanging(string value);
    partial void OnErrorLoginMachineNameChanged();
    #endregion
		
		public ErrorLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogNo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ErrorLogNo
		{
			get
			{
				return this._ErrorLogNo;
			}
			set
			{
				if ((this._ErrorLogNo != value))
				{
					this.OnErrorLogNoChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogNo = value;
					this.SendPropertyChanged("ErrorLogNo");
					this.OnErrorLogNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMethod", DbType="VarChar(250)")]
		public string ErrorMethod
		{
			get
			{
				return this._ErrorMethod;
			}
			set
			{
				if ((this._ErrorMethod != value))
				{
					this.OnErrorMethodChanging(value);
					this.SendPropertyChanging();
					this._ErrorMethod = value;
					this.SendPropertyChanged("ErrorMethod");
					this.OnErrorMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogMessage", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ErrorLogMessage
		{
			get
			{
				return this._ErrorLogMessage;
			}
			set
			{
				if ((this._ErrorLogMessage != value))
				{
					this.OnErrorLogMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogMessage = value;
					this.SendPropertyChanged("ErrorLogMessage");
					this.OnErrorLogMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogScreen", DbType="VarChar(255)")]
		public string ErrorLogScreen
		{
			get
			{
				return this._ErrorLogScreen;
			}
			set
			{
				if ((this._ErrorLogScreen != value))
				{
					this.OnErrorLogScreenChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogScreen = value;
					this.SendPropertyChanged("ErrorLogScreen");
					this.OnErrorLogScreenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ErrorLogDateTime
		{
			get
			{
				return this._ErrorLogDateTime;
			}
			set
			{
				if ((this._ErrorLogDateTime != value))
				{
					this.OnErrorLogDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogDateTime = value;
					this.SendPropertyChanged("ErrorLogDateTime");
					this.OnErrorLogDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogBy", DbType="VarChar(50)")]
		public string ErrorLogBy
		{
			get
			{
				return this._ErrorLogBy;
			}
			set
			{
				if ((this._ErrorLogBy != value))
				{
					this.OnErrorLogByChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogBy = value;
					this.SendPropertyChanged("ErrorLogBy");
					this.OnErrorLogByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMachineName", DbType="VarChar(50)")]
		public string ErrorMachineName
		{
			get
			{
				return this._ErrorMachineName;
			}
			set
			{
				if ((this._ErrorMachineName != value))
				{
					this.OnErrorMachineNameChanging(value);
					this.SendPropertyChanging();
					this._ErrorMachineName = value;
					this.SendPropertyChanged("ErrorMachineName");
					this.OnErrorMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLoginMachineName", DbType="VarChar(50)")]
		public string ErrorLoginMachineName
		{
			get
			{
				return this._ErrorLoginMachineName;
			}
			set
			{
				if ((this._ErrorLoginMachineName != value))
				{
					this.OnErrorLoginMachineNameChanging(value);
					this.SendPropertyChanging();
					this._ErrorLoginMachineName = value;
					this.SendPropertyChanged("ErrorLoginMachineName");
					this.OnErrorLoginMachineNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Layout_Screen")]
	public partial class Layout_Screen
	{
		
		private string _UserID;
		
		private string _Screen;
		
		private string _Control;
		
		private string _MType;
		
		private string _C_Columns;
		
		private System.Nullable<decimal> _W_width;
		
		private System.Nullable<decimal> _H_higth;
		
		private System.Nullable<decimal> _Seq;
		
		public Layout_Screen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Screen", DbType="NVarChar(50)")]
		public string Screen
		{
			get
			{
				return this._Screen;
			}
			set
			{
				if ((this._Screen != value))
				{
					this._Screen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Control", DbType="NVarChar(50)")]
		public string Control
		{
			get
			{
				return this._Control;
			}
			set
			{
				if ((this._Control != value))
				{
					this._Control = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MType", DbType="NVarChar(20)")]
		public string MType
		{
			get
			{
				return this._MType;
			}
			set
			{
				if ((this._MType != value))
				{
					this._MType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Columns", DbType="NVarChar(50)")]
		public string C_Columns
		{
			get
			{
				return this._C_Columns;
			}
			set
			{
				if ((this._C_Columns != value))
				{
					this._C_Columns = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W_width", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> W_width
		{
			get
			{
				return this._W_width;
			}
			set
			{
				if ((this._W_width != value))
				{
					this._W_width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_higth", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> H_higth
		{
			get
			{
				return this._H_higth;
			}
			set
			{
				if ((this._H_higth != value))
				{
					this._H_higth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seq", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Seq
		{
			get
			{
				return this._Seq;
			}
			set
			{
				if ((this._Seq != value))
				{
					this._Seq = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OpenForm")]
	public partial class OpenForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RootName;
		
		private string _NodeName;
		
		private string _TypeNode;
		
		private string _TextNode;
		
		private string _LinkNode;
		
		private System.Nullable<bool> _DialogFlag;
		
		private string _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRootNameChanging(string value);
    partial void OnRootNameChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnTypeNodeChanging(string value);
    partial void OnTypeNodeChanged();
    partial void OnTextNodeChanging(string value);
    partial void OnTextNodeChanged();
    partial void OnLinkNodeChanging(string value);
    partial void OnLinkNodeChanged();
    partial void OnDialogFlagChanging(System.Nullable<bool> value);
    partial void OnDialogFlagChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    #endregion
		
		public OpenForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootName", DbType="VarChar(50)")]
		public string RootName
		{
			get
			{
				return this._RootName;
			}
			set
			{
				if ((this._RootName != value))
				{
					this.OnRootNameChanging(value);
					this.SendPropertyChanging();
					this._RootName = value;
					this.SendPropertyChanged("RootName");
					this.OnRootNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="VarChar(50)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this.OnNodeNameChanging(value);
					this.SendPropertyChanging();
					this._NodeName = value;
					this.SendPropertyChanged("NodeName");
					this.OnNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNode", DbType="VarChar(50)")]
		public string TypeNode
		{
			get
			{
				return this._TypeNode;
			}
			set
			{
				if ((this._TypeNode != value))
				{
					this.OnTypeNodeChanging(value);
					this.SendPropertyChanging();
					this._TypeNode = value;
					this.SendPropertyChanged("TypeNode");
					this.OnTypeNodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextNode", DbType="VarChar(50)")]
		public string TextNode
		{
			get
			{
				return this._TextNode;
			}
			set
			{
				if ((this._TextNode != value))
				{
					this.OnTextNodeChanging(value);
					this.SendPropertyChanging();
					this._TextNode = value;
					this.SendPropertyChanged("TextNode");
					this.OnTextNodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkNode", DbType="VarChar(1000)")]
		public string LinkNode
		{
			get
			{
				return this._LinkNode;
			}
			set
			{
				if ((this._LinkNode != value))
				{
					this.OnLinkNodeChanging(value);
					this.SendPropertyChanging();
					this._LinkNode = value;
					this.SendPropertyChanged("LinkNode");
					this.OnLinkNodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DialogFlag", DbType="Bit")]
		public System.Nullable<bool> DialogFlag
		{
			get
			{
				return this._DialogFlag;
			}
			set
			{
				if ((this._DialogFlag != value))
				{
					this.OnDialogFlagChanging(value);
					this.SendPropertyChanging();
					this._DialogFlag = value;
					this.SendPropertyChanged("DialogFlag");
					this.OnDialogFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_History")]
	public partial class tb_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ScreenName;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _ApplicationNme;
		
		private string _Detail;
		
		private string _RefNo;
		
		private string _CreateBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnScreenNameChanging(string value);
    partial void OnScreenNameChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnApplicationNmeChanging(string value);
    partial void OnApplicationNmeChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    partial void OnRefNoChanging(string value);
    partial void OnRefNoChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
		
		public tb_History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenName", DbType="NVarChar(50)")]
		public string ScreenName
		{
			get
			{
				return this._ScreenName;
			}
			set
			{
				if ((this._ScreenName != value))
				{
					this.OnScreenNameChanging(value);
					this.SendPropertyChanging();
					this._ScreenName = value;
					this.SendPropertyChanged("ScreenName");
					this.OnScreenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationNme", DbType="NVarChar(50)")]
		public string ApplicationNme
		{
			get
			{
				return this._ApplicationNme;
			}
			set
			{
				if ((this._ApplicationNme != value))
				{
					this.OnApplicationNmeChanging(value);
					this.SendPropertyChanging();
					this._ApplicationNme = value;
					this.SendPropertyChanged("ApplicationNme");
					this.OnApplicationNmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(550)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNo", DbType="NVarChar(50)")]
		public string RefNo
		{
			get
			{
				return this._RefNo;
			}
			set
			{
				if ((this._RefNo != value))
				{
					this.OnRefNoChanging(value);
					this.SendPropertyChanging();
					this._RefNo = value;
					this.SendPropertyChanged("RefNo");
					this.OnRefNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Path")]
	public partial class tb_Path : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _PathCode;
		
		private string _PathDetail;
		
		private string _PathFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPathCodeChanging(string value);
    partial void OnPathCodeChanged();
    partial void OnPathDetailChanging(string value);
    partial void OnPathDetailChanged();
    partial void OnPathFileChanging(string value);
    partial void OnPathFileChanged();
    #endregion
		
		public tb_Path()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathCode", DbType="VarChar(50)")]
		public string PathCode
		{
			get
			{
				return this._PathCode;
			}
			set
			{
				if ((this._PathCode != value))
				{
					this.OnPathCodeChanging(value);
					this.SendPropertyChanging();
					this._PathCode = value;
					this.SendPropertyChanged("PathCode");
					this.OnPathCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathDetail", DbType="VarChar(150)")]
		public string PathDetail
		{
			get
			{
				return this._PathDetail;
			}
			set
			{
				if ((this._PathDetail != value))
				{
					this.OnPathDetailChanging(value);
					this.SendPropertyChanging();
					this._PathDetail = value;
					this.SendPropertyChanged("PathDetail");
					this.OnPathDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathFile", DbType="NVarChar(550)")]
		public string PathFile
		{
			get
			{
				return this._PathFile;
			}
			set
			{
				if ((this._PathFile != value))
				{
					this.OnPathFileChanging(value);
					this.SendPropertyChanging();
					this._PathFile = value;
					this.SendPropertyChanged("PathFile");
					this.OnPathFileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_WorkDays")]
	public partial class tb_WorkDay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YYYY;
		
		private int _MMM;
		
		private System.Nullable<decimal> _WorkDays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYYYYChanging(int value);
    partial void OnYYYYChanged();
    partial void OnMMMChanging(int value);
    partial void OnMMMChanged();
    partial void OnWorkDaysChanging(System.Nullable<decimal> value);
    partial void OnWorkDaysChanged();
    #endregion
		
		public tb_WorkDay()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYYY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int YYYY
		{
			get
			{
				return this._YYYY;
			}
			set
			{
				if ((this._YYYY != value))
				{
					this.OnYYYYChanging(value);
					this.SendPropertyChanging();
					this._YYYY = value;
					this.SendPropertyChanged("YYYY");
					this.OnYYYYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MMM
		{
			get
			{
				return this._MMM;
			}
			set
			{
				if ((this._MMM != value))
				{
					this.OnMMMChanging(value);
					this.SendPropertyChanging();
					this._MMM = value;
					this.SendPropertyChanged("MMM");
					this.OnMMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkDays", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WorkDays
		{
			get
			{
				return this._WorkDays;
			}
			set
			{
				if ((this._WorkDays != value))
				{
					this.OnWorkDaysChanging(value);
					this.SendPropertyChanging();
					this._WorkDays = value;
					this.SendPropertyChanged("WorkDays");
					this.OnWorkDaysChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_WorkHour")]
	public partial class tb_WorkHour
	{
		
		private System.Nullable<decimal> _WorkHour;
		
		public tb_WorkHour()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkHour", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WorkHour
		{
			get
			{
				return this._WorkHour;
			}
			set
			{
				if ((this._WorkHour != value))
				{
					this._WorkHour = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_LocationlWH")]
	public partial class tb_LocationlWH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
		
		public tb_LocationlWH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_User")]
	public partial class tb_User
	{
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		public tb_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ListQueue")]
	public partial class tb_ListQueue
	{
		
		private int _id;
		
		private string _ListType;
		
		private string _ListApp;
		
		private string _ListName;
		
		private string _ListDescription;
		
		private string _Status;
		
		private string _ListRefNo;
		
		private System.Nullable<System.DateTime> _Createdate;
		
		private string _CreateBy;
		
		public tb_ListQueue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListType", DbType="NVarChar(50)")]
		public string ListType
		{
			get
			{
				return this._ListType;
			}
			set
			{
				if ((this._ListType != value))
				{
					this._ListType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListApp", DbType="NVarChar(50)")]
		public string ListApp
		{
			get
			{
				return this._ListApp;
			}
			set
			{
				if ((this._ListApp != value))
				{
					this._ListApp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListName", DbType="NVarChar(100)")]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListDescription", DbType="NVarChar(50)")]
		public string ListDescription
		{
			get
			{
				return this._ListDescription;
			}
			set
			{
				if ((this._ListDescription != value))
				{
					this._ListDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListRefNo", DbType="NVarChar(50)")]
		public string ListRefNo
		{
			get
			{
				return this._ListRefNo;
			}
			set
			{
				if ((this._ListRefNo != value))
				{
					this._ListRefNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Createdate
		{
			get
			{
				return this._Createdate;
			}
			set
			{
				if ((this._Createdate != value))
				{
					this._Createdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ReceiveHD")]
	public partial class tb_ReceiveHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _RCNo;
		
		private string _RCVendorNo;
		
		private string _RCVendorName;
		
		private string _RCInvoiceNo;
		
		private string _RCStatus;
		
		private string _RCRemark;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnRCNoChanging(string value);
    partial void OnRCNoChanged();
    partial void OnRCVendorNoChanging(string value);
    partial void OnRCVendorNoChanged();
    partial void OnRCVendorNameChanging(string value);
    partial void OnRCVendorNameChanged();
    partial void OnRCInvoiceNoChanging(string value);
    partial void OnRCInvoiceNoChanged();
    partial void OnRCStatusChanging(string value);
    partial void OnRCStatusChanged();
    partial void OnRCRemarkChanging(string value);
    partial void OnRCRemarkChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    #endregion
		
		public tb_ReceiveHD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RCNo
		{
			get
			{
				return this._RCNo;
			}
			set
			{
				if ((this._RCNo != value))
				{
					this.OnRCNoChanging(value);
					this.SendPropertyChanging();
					this._RCNo = value;
					this.SendPropertyChanged("RCNo");
					this.OnRCNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCVendorNo", DbType="NVarChar(50)")]
		public string RCVendorNo
		{
			get
			{
				return this._RCVendorNo;
			}
			set
			{
				if ((this._RCVendorNo != value))
				{
					this.OnRCVendorNoChanging(value);
					this.SendPropertyChanging();
					this._RCVendorNo = value;
					this.SendPropertyChanged("RCVendorNo");
					this.OnRCVendorNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCVendorName", DbType="NVarChar(50)")]
		public string RCVendorName
		{
			get
			{
				return this._RCVendorName;
			}
			set
			{
				if ((this._RCVendorName != value))
				{
					this.OnRCVendorNameChanging(value);
					this.SendPropertyChanging();
					this._RCVendorName = value;
					this.SendPropertyChanged("RCVendorName");
					this.OnRCVendorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCInvoiceNo", DbType="NVarChar(50)")]
		public string RCInvoiceNo
		{
			get
			{
				return this._RCInvoiceNo;
			}
			set
			{
				if ((this._RCInvoiceNo != value))
				{
					this.OnRCInvoiceNoChanging(value);
					this.SendPropertyChanging();
					this._RCInvoiceNo = value;
					this.SendPropertyChanged("RCInvoiceNo");
					this.OnRCInvoiceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCStatus", DbType="NVarChar(50)")]
		public string RCStatus
		{
			get
			{
				return this._RCStatus;
			}
			set
			{
				if ((this._RCStatus != value))
				{
					this.OnRCStatusChanging(value);
					this.SendPropertyChanging();
					this._RCStatus = value;
					this.SendPropertyChanged("RCStatus");
					this.OnRCStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCRemark", DbType="NVarChar(50)")]
		public string RCRemark
		{
			get
			{
				return this._RCRemark;
			}
			set
			{
				if ((this._RCRemark != value))
				{
					this.OnRCRemarkChanging(value);
					this.SendPropertyChanging();
					this._RCRemark = value;
					this.SendPropertyChanged("RCRemark");
					this.OnRCRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Sp_ADM03_OpenFormSelectResult
	{
		
		private int _ID;
		
		private string _RootName;
		
		private string _NodeName;
		
		private string _TypeNode;
		
		private string _TextNode;
		
		private string _LinkNode;
		
		private System.Nullable<bool> _DialogFlag;
		
		private string _Version;
		
		public Sp_ADM03_OpenFormSelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootName", DbType="VarChar(50)")]
		public string RootName
		{
			get
			{
				return this._RootName;
			}
			set
			{
				if ((this._RootName != value))
				{
					this._RootName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="VarChar(50)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this._NodeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNode", DbType="VarChar(50)")]
		public string TypeNode
		{
			get
			{
				return this._TypeNode;
			}
			set
			{
				if ((this._TypeNode != value))
				{
					this._TypeNode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextNode", DbType="VarChar(50)")]
		public string TextNode
		{
			get
			{
				return this._TextNode;
			}
			set
			{
				if ((this._TextNode != value))
				{
					this._TextNode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkNode", DbType="VarChar(1000)")]
		public string LinkNode
		{
			get
			{
				return this._LinkNode;
			}
			set
			{
				if ((this._LinkNode != value))
				{
					this._LinkNode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DialogFlag", DbType="Bit")]
		public System.Nullable<bool> DialogFlag
		{
			get
			{
				return this._DialogFlag;
			}
			set
			{
				if ((this._DialogFlag != value))
				{
					this._DialogFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
	}
	
	public partial class sp_001_TPIC_SelectItemResult
	{
		
		private string _CODE;
		
		private string _BUNR;
		
		private string _BUMO;
		
		private decimal _Leadtime;
		
		private string _VENDOR;
		
		private string _HOKAN;
		
		private decimal _SNP;
		
		private string _INC;
		
		public sp_001_TPIC_SelectItemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUNR", DbType="NVarChar(12)")]
		public string BUNR
		{
			get
			{
				return this._BUNR;
			}
			set
			{
				if ((this._BUNR != value))
				{
					this._BUNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUMO", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string BUMO
		{
			get
			{
				return this._BUMO;
			}
			set
			{
				if ((this._BUMO != value))
				{
					this._BUMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leadtime", DbType="Decimal(29,0) NOT NULL")]
		public decimal Leadtime
		{
			get
			{
				return this._Leadtime;
			}
			set
			{
				if ((this._Leadtime != value))
				{
					this._Leadtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string VENDOR
		{
			get
			{
				return this._VENDOR;
			}
			set
			{
				if ((this._VENDOR != value))
				{
					this._VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOKAN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HOKAN
		{
			get
			{
				return this._HOKAN;
			}
			set
			{
				if ((this._HOKAN != value))
				{
					this._HOKAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNP", DbType="Decimal(29,2) NOT NULL")]
		public decimal SNP
		{
			get
			{
				return this._SNP;
			}
			set
			{
				if ((this._SNP != value))
				{
					this._SNP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC", DbType="NVarChar(10)")]
		public string INC
		{
			get
			{
				return this._INC;
			}
			set
			{
				if ((this._INC != value))
				{
					this._INC = value;
				}
			}
		}
	}
	
	public partial class sp_002_TPIC_SelectPOResult
	{
		
		private long _LID;
		
		private string _PORDER;
		
		private string _CODE;
		
		private string _BUMO;
		
		private string _VENDOR;
		
		private decimal _KVOL;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private decimal _PRICE;
		
		private string _INPUTUSER;
		
		public sp_002_TPIC_SelectPOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LID", DbType="BigInt NOT NULL")]
		public long LID
		{
			get
			{
				return this._LID;
			}
			set
			{
				if ((this._LID != value))
				{
					this._LID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PORDER", DbType="NVarChar(18) NOT NULL", CanBeNull=false)]
		public string PORDER
		{
			get
			{
				return this._PORDER;
			}
			set
			{
				if ((this._PORDER != value))
				{
					this._PORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUMO", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string BUMO
		{
			get
			{
				return this._BUMO;
			}
			set
			{
				if ((this._BUMO != value))
				{
					this._BUMO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string VENDOR
		{
			get
			{
				return this._VENDOR;
			}
			set
			{
				if ((this._VENDOR != value))
				{
					this._VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KVOL", DbType="Decimal(29,2) NOT NULL")]
		public decimal KVOL
		{
			get
			{
				return this._KVOL;
			}
			set
			{
				if ((this._KVOL != value))
				{
					this._KVOL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(29,4) NOT NULL")]
		public decimal PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUTUSER", DbType="NVarChar(20)")]
		public string INPUTUSER
		{
			get
			{
				return this._INPUTUSER;
			}
			set
			{
				if ((this._INPUTUSER != value))
				{
					this._INPUTUSER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
